### ISSUE TITLE
MainInterface - Pop up window does not close when use firefox

### ISSUE THREAD

**Issue by thetonymaster** [Infrastructure-Solutions/website#28]
The popup does not close when using a firefox or firefox-like browsers

**Comment by iLeonelPerea** [comment]
Console error:

TypeError: undefined is not an object (evaluating 'that._oauthWindow.location.href.includes')
TypeError: undefined is not an object (evaluating 'data.document.body.getElementsByTagName("pre")[0].innerHTML')
